import localFont from 'next/font/local';
import './globals.css';

import Providers from './providers';
import Navbar from '@/components/custom/Navbar';
import { Toaster } from '@/components/ui/sonner';
import AuthInit from '@/components/custom/AuthInit';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Toaster />
          <Navbar />
          <AuthInit />
          {children}
        </Providers>
      </body>
    </html>
  );
}
